# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/769/bin/cmake

# The command to remove a file.
RM = /snap/cmake/769/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ram/zhetapi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ram/zhetapi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/769/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/715/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ram/zhetapi/CMakeFiles /home/ram/zhetapi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ram/zhetapi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named port

# Build rule for target.
port: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port
.PHONY : port

# fast build rule for target.
port/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port.dir/build.make CMakeFiles/port.dir/build
.PHONY : port/fast

#=============================================================================
# Target rules for targets named timer

# Build rule for target.
timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timer
.PHONY : timer

# fast build rule for target.
timer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/build
.PHONY : timer/fast

#=============================================================================
# Target rules for targets named port_function

# Build rule for target.
port_function: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port_function
.PHONY : port_function

# fast build rule for target.
port_function/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_function.dir/build.make CMakeFiles/port_function.dir/build
.PHONY : port_function/fast

#=============================================================================
# Target rules for targets named port_tensor

# Build rule for target.
port_tensor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port_tensor
.PHONY : port_tensor

# fast build rule for target.
port_tensor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_tensor.dir/build.make CMakeFiles/port_tensor.dir/build
.PHONY : port_tensor/fast

#=============================================================================
# Target rules for targets named zhp-static

# Build rule for target.
zhp-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zhp-static
.PHONY : zhp-static

# fast build rule for target.
zhp-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/build
.PHONY : zhp-static/fast

#=============================================================================
# Target rules for targets named zhp-shared

# Build rule for target.
zhp-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zhp-shared
.PHONY : zhp-shared

# fast build rule for target.
zhp-shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/build
.PHONY : zhp-shared/fast

#=============================================================================
# Target rules for targets named cuda

# Build rule for target.
cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda
.PHONY : cuda

# fast build rule for target.
cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/build
.PHONY : cuda/fast

#=============================================================================
# Target rules for targets named czhp

# Build rule for target.
czhp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 czhp
.PHONY : czhp

# fast build rule for target.
czhp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/build
.PHONY : czhp/fast

#=============================================================================
# Target rules for targets named port_matrix

# Build rule for target.
port_matrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port_matrix
.PHONY : port_matrix

# fast build rule for target.
port_matrix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_matrix.dir/build.make CMakeFiles/port_matrix.dir/build
.PHONY : port_matrix/fast

#=============================================================================
# Target rules for targets named port_vector

# Build rule for target.
port_vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port_vector
.PHONY : port_vector

# fast build rule for target.
port_vector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_vector.dir/build.make CMakeFiles/port_vector.dir/build
.PHONY : port_vector/fast

#=============================================================================
# Target rules for targets named zhetapi

# Build rule for target.
zhetapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zhetapi
.PHONY : zhetapi

# fast build rule for target.
zhetapi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhetapi.dir/build.make CMakeFiles/zhetapi.dir/build
.PHONY : zhetapi/fast

#=============================================================================
# Target rules for targets named exp

# Build rule for target.
exp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exp
.PHONY : exp

# fast build rule for target.
exp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exp.dir/build.make CMakeFiles/exp.dir/build
.PHONY : exp/fast

source/algorithm.o: source/algorithm.cpp.o

.PHONY : source/algorithm.o

# target to build an object file
source/algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/algorithm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/algorithm.cpp.o
.PHONY : source/algorithm.cpp.o

source/algorithm.i: source/algorithm.cpp.i

.PHONY : source/algorithm.i

# target to preprocess a source file
source/algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/algorithm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/algorithm.cpp.i
.PHONY : source/algorithm.cpp.i

source/algorithm.s: source/algorithm.cpp.s

.PHONY : source/algorithm.s

# target to generate assembly for a file
source/algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/algorithm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/algorithm.cpp.s
.PHONY : source/algorithm.cpp.s

source/barn.o: source/barn.cpp.o

.PHONY : source/barn.o

# target to build an object file
source/barn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/barn.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/barn.cpp.o
.PHONY : source/barn.cpp.o

source/barn.i: source/barn.cpp.i

.PHONY : source/barn.i

# target to preprocess a source file
source/barn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/barn.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/barn.cpp.i
.PHONY : source/barn.cpp.i

source/barn.s: source/barn.cpp.s

.PHONY : source/barn.s

# target to generate assembly for a file
source/barn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/barn.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/barn.cpp.s
.PHONY : source/barn.cpp.s

source/builtin/basic_io.o: source/builtin/basic_io.cpp.o

.PHONY : source/builtin/basic_io.o

# target to build an object file
source/builtin/basic_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/builtin/basic_io.cpp.o
.PHONY : source/builtin/basic_io.cpp.o

source/builtin/basic_io.i: source/builtin/basic_io.cpp.i

.PHONY : source/builtin/basic_io.i

# target to preprocess a source file
source/builtin/basic_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/builtin/basic_io.cpp.i
.PHONY : source/builtin/basic_io.cpp.i

source/builtin/basic_io.s: source/builtin/basic_io.cpp.s

.PHONY : source/builtin/basic_io.s

# target to generate assembly for a file
source/builtin/basic_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/builtin/basic_io.cpp.s
.PHONY : source/builtin/basic_io.cpp.s

source/class.o: source/class.cpp.o

.PHONY : source/class.o

# target to build an object file
source/class.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/class.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/class.cpp.o
.PHONY : source/class.cpp.o

source/class.i: source/class.cpp.i

.PHONY : source/class.i

# target to preprocess a source file
source/class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/class.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/class.cpp.i
.PHONY : source/class.cpp.i

source/class.s: source/class.cpp.s

.PHONY : source/class.s

# target to generate assembly for a file
source/class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/class.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/class.cpp.s
.PHONY : source/class.cpp.s

source/cli/cli.o: source/cli/cli.cpp.o

.PHONY : source/cli/cli.o

# target to build an object file
source/cli/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhetapi.dir/build.make CMakeFiles/zhetapi.dir/source/cli/cli.cpp.o
.PHONY : source/cli/cli.cpp.o

source/cli/cli.i: source/cli/cli.cpp.i

.PHONY : source/cli/cli.i

# target to preprocess a source file
source/cli/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhetapi.dir/build.make CMakeFiles/zhetapi.dir/source/cli/cli.cpp.i
.PHONY : source/cli/cli.cpp.i

source/cli/cli.s: source/cli/cli.cpp.s

.PHONY : source/cli/cli.s

# target to generate assembly for a file
source/cli/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhetapi.dir/build.make CMakeFiles/zhetapi.dir/source/cli/cli.cpp.s
.PHONY : source/cli/cli.cpp.s

source/complex.o: source/complex.cpp.o

.PHONY : source/complex.o

# target to build an object file
source/complex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/complex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/complex.cpp.o
.PHONY : source/complex.cpp.o

source/complex.i: source/complex.cpp.i

.PHONY : source/complex.i

# target to preprocess a source file
source/complex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/complex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/complex.cpp.i
.PHONY : source/complex.cpp.i

source/complex.s: source/complex.cpp.s

.PHONY : source/complex.s

# target to generate assembly for a file
source/complex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/complex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/complex.cpp.s
.PHONY : source/complex.cpp.s

source/cuda/main.o: source/cuda/main.cu.o

.PHONY : source/cuda/main.o

# target to build an object file
source/cuda/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/source/cuda/main.cu.o
.PHONY : source/cuda/main.cu.o

source/cuda/main.i: source/cuda/main.cu.i

.PHONY : source/cuda/main.i

# target to preprocess a source file
source/cuda/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/source/cuda/main.cu.i
.PHONY : source/cuda/main.cu.i

source/cuda/main.s: source/cuda/main.cu.s

.PHONY : source/cuda/main.s

# target to generate assembly for a file
source/cuda/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/source/cuda/main.cu.s
.PHONY : source/cuda/main.cu.s

source/czhp/czhp.o: source/czhp/czhp.cpp.o

.PHONY : source/czhp/czhp.o

# target to build an object file
source/czhp/czhp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/czhp.cpp.o
.PHONY : source/czhp/czhp.cpp.o

source/czhp/czhp.i: source/czhp/czhp.cpp.i

.PHONY : source/czhp/czhp.i

# target to preprocess a source file
source/czhp/czhp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/czhp.cpp.i
.PHONY : source/czhp/czhp.cpp.i

source/czhp/czhp.s: source/czhp/czhp.cpp.s

.PHONY : source/czhp/czhp.s

# target to generate assembly for a file
source/czhp/czhp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/czhp.cpp.s
.PHONY : source/czhp/czhp.cpp.s

source/czhp/execute.o: source/czhp/execute.cpp.o

.PHONY : source/czhp/execute.o

# target to build an object file
source/czhp/execute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/execute.cpp.o
.PHONY : source/czhp/execute.cpp.o

source/czhp/execute.i: source/czhp/execute.cpp.i

.PHONY : source/czhp/execute.i

# target to preprocess a source file
source/czhp/execute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/execute.cpp.i
.PHONY : source/czhp/execute.cpp.i

source/czhp/execute.s: source/czhp/execute.cpp.s

.PHONY : source/czhp/execute.s

# target to generate assembly for a file
source/czhp/execute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/execute.cpp.s
.PHONY : source/czhp/execute.cpp.s

source/czhp/library.o: source/czhp/library.cpp.o

.PHONY : source/czhp/library.o

# target to build an object file
source/czhp/library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/library.cpp.o
.PHONY : source/czhp/library.cpp.o

source/czhp/library.i: source/czhp/library.cpp.i

.PHONY : source/czhp/library.i

# target to preprocess a source file
source/czhp/library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/library.cpp.i
.PHONY : source/czhp/library.cpp.i

source/czhp/library.s: source/czhp/library.cpp.s

.PHONY : source/czhp/library.s

# target to generate assembly for a file
source/czhp/library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/library.cpp.s
.PHONY : source/czhp/library.cpp.s

source/czhp/parser.o: source/czhp/parser.cpp.o

.PHONY : source/czhp/parser.o

# target to build an object file
source/czhp/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/parser.cpp.o
.PHONY : source/czhp/parser.cpp.o

source/czhp/parser.i: source/czhp/parser.cpp.i

.PHONY : source/czhp/parser.i

# target to preprocess a source file
source/czhp/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/parser.cpp.i
.PHONY : source/czhp/parser.cpp.i

source/czhp/parser.s: source/czhp/parser.cpp.s

.PHONY : source/czhp/parser.s

# target to generate assembly for a file
source/czhp/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/czhp.dir/build.make CMakeFiles/czhp.dir/source/czhp/parser.cpp.s
.PHONY : source/czhp/parser.cpp.s

source/display.o: source/display.cpp.o

.PHONY : source/display.o

# target to build an object file
source/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/display.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/display.cpp.o
.PHONY : source/display.cpp.o

source/display.i: source/display.cpp.i

.PHONY : source/display.i

# target to preprocess a source file
source/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/display.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/display.cpp.i
.PHONY : source/display.cpp.i

source/display.s: source/display.cpp.s

.PHONY : source/display.s

# target to generate assembly for a file
source/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/display.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/display.cpp.s
.PHONY : source/display.cpp.s

source/exp/exp.o: source/exp/exp.cpp.o

.PHONY : source/exp/exp.o

# target to build an object file
source/exp/exp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exp.dir/build.make CMakeFiles/exp.dir/source/exp/exp.cpp.o
.PHONY : source/exp/exp.cpp.o

source/exp/exp.i: source/exp/exp.cpp.i

.PHONY : source/exp/exp.i

# target to preprocess a source file
source/exp/exp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exp.dir/build.make CMakeFiles/exp.dir/source/exp/exp.cpp.i
.PHONY : source/exp/exp.cpp.i

source/exp/exp.s: source/exp/exp.cpp.s

.PHONY : source/exp/exp.s

# target to generate assembly for a file
source/exp/exp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exp.dir/build.make CMakeFiles/exp.dir/source/exp/exp.cpp.s
.PHONY : source/exp/exp.cpp.s

source/function.o: source/function.cpp.o

.PHONY : source/function.o

# target to build an object file
source/function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/function.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/function.cpp.o
.PHONY : source/function.cpp.o

source/function.i: source/function.cpp.i

.PHONY : source/function.i

# target to preprocess a source file
source/function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/function.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/function.cpp.i
.PHONY : source/function.cpp.i

source/function.s: source/function.cpp.s

.PHONY : source/function.s

# target to generate assembly for a file
source/function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/function.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/function.cpp.s
.PHONY : source/function.cpp.s

source/label.o: source/label.cpp.o

.PHONY : source/label.o

# target to build an object file
source/label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/label.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/label.cpp.o
.PHONY : source/label.cpp.o

source/label.i: source/label.cpp.i

.PHONY : source/label.i

# target to preprocess a source file
source/label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/label.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/label.cpp.i
.PHONY : source/label.cpp.i

source/label.s: source/label.cpp.s

.PHONY : source/label.s

# target to generate assembly for a file
source/label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/label.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/label.cpp.s
.PHONY : source/label.cpp.s

source/node.o: source/node.cpp.o

.PHONY : source/node.o

# target to build an object file
source/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node.cpp.o
.PHONY : source/node.cpp.o

source/node.i: source/node.cpp.i

.PHONY : source/node.i

# target to preprocess a source file
source/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node.cpp.i
.PHONY : source/node.cpp.i

source/node.s: source/node.cpp.s

.PHONY : source/node.s

# target to generate assembly for a file
source/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node.cpp.s
.PHONY : source/node.cpp.s

source/node_differentiation.o: source/node_differentiation.cpp.o

.PHONY : source/node_differentiation.o

# target to build an object file
source/node_differentiation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_differentiation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_differentiation.cpp.o
.PHONY : source/node_differentiation.cpp.o

source/node_differentiation.i: source/node_differentiation.cpp.i

.PHONY : source/node_differentiation.i

# target to preprocess a source file
source/node_differentiation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_differentiation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_differentiation.cpp.i
.PHONY : source/node_differentiation.cpp.i

source/node_differentiation.s: source/node_differentiation.cpp.s

.PHONY : source/node_differentiation.s

# target to generate assembly for a file
source/node_differentiation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_differentiation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_differentiation.cpp.s
.PHONY : source/node_differentiation.cpp.s

source/node_manager.o: source/node_manager.cpp.o

.PHONY : source/node_manager.o

# target to build an object file
source/node_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_manager.cpp.o
.PHONY : source/node_manager.cpp.o

source/node_manager.i: source/node_manager.cpp.i

.PHONY : source/node_manager.i

# target to preprocess a source file
source/node_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_manager.cpp.i
.PHONY : source/node_manager.cpp.i

source/node_manager.s: source/node_manager.cpp.s

.PHONY : source/node_manager.s

# target to generate assembly for a file
source/node_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_manager.cpp.s
.PHONY : source/node_manager.cpp.s

source/node_reference.o: source/node_reference.cpp.o

.PHONY : source/node_reference.o

# target to build an object file
source/node_reference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_reference.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_reference.cpp.o
.PHONY : source/node_reference.cpp.o

source/node_reference.i: source/node_reference.cpp.i

.PHONY : source/node_reference.i

# target to preprocess a source file
source/node_reference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_reference.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_reference.cpp.i
.PHONY : source/node_reference.cpp.i

source/node_reference.s: source/node_reference.cpp.s

.PHONY : source/node_reference.s

# target to generate assembly for a file
source/node_reference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/node_reference.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/node_reference.cpp.s
.PHONY : source/node_reference.cpp.s

source/operation.o: source/operation.cpp.o

.PHONY : source/operation.o

# target to build an object file
source/operation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation.cpp.o
.PHONY : source/operation.cpp.o

source/operation.i: source/operation.cpp.i

.PHONY : source/operation.i

# target to preprocess a source file
source/operation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation.cpp.i
.PHONY : source/operation.cpp.i

source/operation.s: source/operation.cpp.s

.PHONY : source/operation.s

# target to generate assembly for a file
source/operation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation.cpp.s
.PHONY : source/operation.cpp.s

source/operation_holder.o: source/operation_holder.cpp.o

.PHONY : source/operation_holder.o

# target to build an object file
source/operation_holder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation_holder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation_holder.cpp.o
.PHONY : source/operation_holder.cpp.o

source/operation_holder.i: source/operation_holder.cpp.i

.PHONY : source/operation_holder.i

# target to preprocess a source file
source/operation_holder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation_holder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation_holder.cpp.i
.PHONY : source/operation_holder.cpp.i

source/operation_holder.s: source/operation_holder.cpp.s

.PHONY : source/operation_holder.s

# target to generate assembly for a file
source/operation_holder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/operation_holder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/operation_holder.cpp.s
.PHONY : source/operation_holder.cpp.s

source/port/port-function.o: source/port/port-function.cpp.o

.PHONY : source/port/port-function.o

# target to build an object file
source/port/port-function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_function.dir/build.make CMakeFiles/port_function.dir/source/port/port-function.cpp.o
.PHONY : source/port/port-function.cpp.o

source/port/port-function.i: source/port/port-function.cpp.i

.PHONY : source/port/port-function.i

# target to preprocess a source file
source/port/port-function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_function.dir/build.make CMakeFiles/port_function.dir/source/port/port-function.cpp.i
.PHONY : source/port/port-function.cpp.i

source/port/port-function.s: source/port/port-function.cpp.s

.PHONY : source/port/port-function.s

# target to generate assembly for a file
source/port/port-function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_function.dir/build.make CMakeFiles/port_function.dir/source/port/port-function.cpp.s
.PHONY : source/port/port-function.cpp.s

source/port/port-matrix.o: source/port/port-matrix.cpp.o

.PHONY : source/port/port-matrix.o

# target to build an object file
source/port/port-matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_matrix.dir/build.make CMakeFiles/port_matrix.dir/source/port/port-matrix.cpp.o
.PHONY : source/port/port-matrix.cpp.o

source/port/port-matrix.i: source/port/port-matrix.cpp.i

.PHONY : source/port/port-matrix.i

# target to preprocess a source file
source/port/port-matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_matrix.dir/build.make CMakeFiles/port_matrix.dir/source/port/port-matrix.cpp.i
.PHONY : source/port/port-matrix.cpp.i

source/port/port-matrix.s: source/port/port-matrix.cpp.s

.PHONY : source/port/port-matrix.s

# target to generate assembly for a file
source/port/port-matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_matrix.dir/build.make CMakeFiles/port_matrix.dir/source/port/port-matrix.cpp.s
.PHONY : source/port/port-matrix.cpp.s

source/port/port-tensor.o: source/port/port-tensor.cpp.o

.PHONY : source/port/port-tensor.o

# target to build an object file
source/port/port-tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_tensor.dir/build.make CMakeFiles/port_tensor.dir/source/port/port-tensor.cpp.o
.PHONY : source/port/port-tensor.cpp.o

source/port/port-tensor.i: source/port/port-tensor.cpp.i

.PHONY : source/port/port-tensor.i

# target to preprocess a source file
source/port/port-tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_tensor.dir/build.make CMakeFiles/port_tensor.dir/source/port/port-tensor.cpp.i
.PHONY : source/port/port-tensor.cpp.i

source/port/port-tensor.s: source/port/port-tensor.cpp.s

.PHONY : source/port/port-tensor.s

# target to generate assembly for a file
source/port/port-tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_tensor.dir/build.make CMakeFiles/port_tensor.dir/source/port/port-tensor.cpp.s
.PHONY : source/port/port-tensor.cpp.s

source/port/port-vector.o: source/port/port-vector.cpp.o

.PHONY : source/port/port-vector.o

# target to build an object file
source/port/port-vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_vector.dir/build.make CMakeFiles/port_vector.dir/source/port/port-vector.cpp.o
.PHONY : source/port/port-vector.cpp.o

source/port/port-vector.i: source/port/port-vector.cpp.i

.PHONY : source/port/port-vector.i

# target to preprocess a source file
source/port/port-vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_vector.dir/build.make CMakeFiles/port_vector.dir/source/port/port-vector.cpp.i
.PHONY : source/port/port-vector.cpp.i

source/port/port-vector.s: source/port/port-vector.cpp.s

.PHONY : source/port/port-vector.s

# target to generate assembly for a file
source/port/port-vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port_vector.dir/build.make CMakeFiles/port_vector.dir/source/port/port-vector.cpp.s
.PHONY : source/port/port-vector.cpp.s

source/port/port.o: source/port/port.cpp.o

.PHONY : source/port/port.o

# target to build an object file
source/port/port.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port.dir/build.make CMakeFiles/port.dir/source/port/port.cpp.o
.PHONY : source/port/port.cpp.o

source/port/port.i: source/port/port.cpp.i

.PHONY : source/port/port.i

# target to preprocess a source file
source/port/port.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port.dir/build.make CMakeFiles/port.dir/source/port/port.cpp.i
.PHONY : source/port/port.cpp.i

source/port/port.s: source/port/port.cpp.s

.PHONY : source/port/port.s

# target to generate assembly for a file
source/port/port.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/port.dir/build.make CMakeFiles/port.dir/source/port/port.cpp.s
.PHONY : source/port/port.cpp.s

source/port/timers.o: source/port/timers.cpp.o

.PHONY : source/port/timers.o

# target to build an object file
source/port/timers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/source/port/timers.cpp.o
.PHONY : source/port/timers.cpp.o

source/port/timers.i: source/port/timers.cpp.i

.PHONY : source/port/timers.i

# target to preprocess a source file
source/port/timers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/source/port/timers.cpp.i
.PHONY : source/port/timers.cpp.i

source/port/timers.s: source/port/timers.cpp.s

.PHONY : source/port/timers.s

# target to generate assembly for a file
source/port/timers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/source/port/timers.cpp.s
.PHONY : source/port/timers.cpp.s

source/registration.o: source/registration.cpp.o

.PHONY : source/registration.o

# target to build an object file
source/registration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/registration.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/registration.cpp.o
.PHONY : source/registration.cpp.o

source/registration.i: source/registration.cpp.i

.PHONY : source/registration.i

# target to preprocess a source file
source/registration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/registration.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/registration.cpp.i
.PHONY : source/registration.cpp.i

source/registration.s: source/registration.cpp.s

.PHONY : source/registration.s

# target to generate assembly for a file
source/registration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/registration.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/registration.cpp.s
.PHONY : source/registration.cpp.s

source/token.o: source/token.cpp.o

.PHONY : source/token.o

# target to build an object file
source/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/token.cpp.o
.PHONY : source/token.cpp.o

source/token.i: source/token.cpp.i

.PHONY : source/token.i

# target to preprocess a source file
source/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/token.cpp.i
.PHONY : source/token.cpp.i

source/token.s: source/token.cpp.s

.PHONY : source/token.s

# target to generate assembly for a file
source/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/token.cpp.s
.PHONY : source/token.cpp.s

source/types.o: source/types.cpp.o

.PHONY : source/types.o

# target to build an object file
source/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/types.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/types.cpp.o
.PHONY : source/types.cpp.o

source/types.i: source/types.cpp.i

.PHONY : source/types.i

# target to preprocess a source file
source/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/types.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/types.cpp.i
.PHONY : source/types.cpp.i

source/types.s: source/types.cpp.s

.PHONY : source/types.s

# target to generate assembly for a file
source/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/types.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/types.cpp.s
.PHONY : source/types.cpp.s

source/variable.o: source/variable.cpp.o

.PHONY : source/variable.o

# target to build an object file
source/variable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable.cpp.o
.PHONY : source/variable.cpp.o

source/variable.i: source/variable.cpp.i

.PHONY : source/variable.i

# target to preprocess a source file
source/variable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable.cpp.i
.PHONY : source/variable.cpp.i

source/variable.s: source/variable.cpp.s

.PHONY : source/variable.s

# target to generate assembly for a file
source/variable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable.cpp.s
.PHONY : source/variable.cpp.s

source/variable_cluster.o: source/variable_cluster.cpp.o

.PHONY : source/variable_cluster.o

# target to build an object file
source/variable_cluster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable_cluster.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable_cluster.cpp.o
.PHONY : source/variable_cluster.cpp.o

source/variable_cluster.i: source/variable_cluster.cpp.i

.PHONY : source/variable_cluster.i

# target to preprocess a source file
source/variable_cluster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable_cluster.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable_cluster.cpp.i
.PHONY : source/variable_cluster.cpp.i

source/variable_cluster.s: source/variable_cluster.cpp.s

.PHONY : source/variable_cluster.s

# target to generate assembly for a file
source/variable_cluster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-static.dir/build.make CMakeFiles/zhp-static.dir/source/variable_cluster.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhp-shared.dir/build.make CMakeFiles/zhp-shared.dir/source/variable_cluster.cpp.s
.PHONY : source/variable_cluster.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuda"
	@echo "... czhp"
	@echo "... exp"
	@echo "... port"
	@echo "... port_function"
	@echo "... port_matrix"
	@echo "... port_tensor"
	@echo "... port_vector"
	@echo "... timer"
	@echo "... zhetapi"
	@echo "... zhp-shared"
	@echo "... zhp-static"
	@echo "... source/algorithm.o"
	@echo "... source/algorithm.i"
	@echo "... source/algorithm.s"
	@echo "... source/barn.o"
	@echo "... source/barn.i"
	@echo "... source/barn.s"
	@echo "... source/builtin/basic_io.o"
	@echo "... source/builtin/basic_io.i"
	@echo "... source/builtin/basic_io.s"
	@echo "... source/class.o"
	@echo "... source/class.i"
	@echo "... source/class.s"
	@echo "... source/cli/cli.o"
	@echo "... source/cli/cli.i"
	@echo "... source/cli/cli.s"
	@echo "... source/complex.o"
	@echo "... source/complex.i"
	@echo "... source/complex.s"
	@echo "... source/cuda/main.o"
	@echo "... source/cuda/main.i"
	@echo "... source/cuda/main.s"
	@echo "... source/czhp/czhp.o"
	@echo "... source/czhp/czhp.i"
	@echo "... source/czhp/czhp.s"
	@echo "... source/czhp/execute.o"
	@echo "... source/czhp/execute.i"
	@echo "... source/czhp/execute.s"
	@echo "... source/czhp/library.o"
	@echo "... source/czhp/library.i"
	@echo "... source/czhp/library.s"
	@echo "... source/czhp/parser.o"
	@echo "... source/czhp/parser.i"
	@echo "... source/czhp/parser.s"
	@echo "... source/display.o"
	@echo "... source/display.i"
	@echo "... source/display.s"
	@echo "... source/exp/exp.o"
	@echo "... source/exp/exp.i"
	@echo "... source/exp/exp.s"
	@echo "... source/function.o"
	@echo "... source/function.i"
	@echo "... source/function.s"
	@echo "... source/label.o"
	@echo "... source/label.i"
	@echo "... source/label.s"
	@echo "... source/node.o"
	@echo "... source/node.i"
	@echo "... source/node.s"
	@echo "... source/node_differentiation.o"
	@echo "... source/node_differentiation.i"
	@echo "... source/node_differentiation.s"
	@echo "... source/node_manager.o"
	@echo "... source/node_manager.i"
	@echo "... source/node_manager.s"
	@echo "... source/node_reference.o"
	@echo "... source/node_reference.i"
	@echo "... source/node_reference.s"
	@echo "... source/operation.o"
	@echo "... source/operation.i"
	@echo "... source/operation.s"
	@echo "... source/operation_holder.o"
	@echo "... source/operation_holder.i"
	@echo "... source/operation_holder.s"
	@echo "... source/port/port-function.o"
	@echo "... source/port/port-function.i"
	@echo "... source/port/port-function.s"
	@echo "... source/port/port-matrix.o"
	@echo "... source/port/port-matrix.i"
	@echo "... source/port/port-matrix.s"
	@echo "... source/port/port-tensor.o"
	@echo "... source/port/port-tensor.i"
	@echo "... source/port/port-tensor.s"
	@echo "... source/port/port-vector.o"
	@echo "... source/port/port-vector.i"
	@echo "... source/port/port-vector.s"
	@echo "... source/port/port.o"
	@echo "... source/port/port.i"
	@echo "... source/port/port.s"
	@echo "... source/port/timers.o"
	@echo "... source/port/timers.i"
	@echo "... source/port/timers.s"
	@echo "... source/registration.o"
	@echo "... source/registration.i"
	@echo "... source/registration.s"
	@echo "... source/token.o"
	@echo "... source/token.i"
	@echo "... source/token.s"
	@echo "... source/types.o"
	@echo "... source/types.i"
	@echo "... source/types.s"
	@echo "... source/variable.o"
	@echo "... source/variable.i"
	@echo "... source/variable.s"
	@echo "... source/variable_cluster.o"
	@echo "... source/variable_cluster.i"
	@echo "... source/variable_cluster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

