#!/bin/bash

if [ "$#" -eq 0 ]; then
	echo "Expected at least one argument"
elif [ $1 = "install" ]; then
	echo "Installing..."

	# Register apps directory
	echo "PATH=${PATH}:$(pwd)/bin" >> .env

	source .env

	# Run cmake
	cmake .
	
	mkdir -p bin

	# Compile and move shared library
	make zhp

	if [ -f "libzhp.so" ]; then
		mv libzhp.so bin/
	fi
	
	# Compile and move apps
	make zhetapi

	mv zhetapi bin/
elif [ $1 = "gdb" ]; then
	echo "Running source/$2.cpp on gdb"

	mkdir -p debug

	g++-8 -g source/testing/$2.cpp -o debug/$2-debug

	gdb ./debug/$2-debug
elif [ $1 = "valgrind" ] || [ $1 = "vgrind" ]; then
	echo "Running source/$2.cpp on valgrind"

	mkdir -p debug

	g++-8 -g source/testing/$2.cpp -o debug/$2-debug

	valgrind ./debug/$2-debug
elif [ $1 = "optimize" ] || [ $1 = "opt" ]; then
	echo "Running source/$2.cpp with optimization"

	mkdir -p debug

	g++-8 -O3 source/testing/$2.cpp -o debug/$2-opt

	./debug/$2-opt
else
	echo "Running source/$1.cpp"

	mkdir -p debug

	g++-8 source/testing/$1.cpp -o debug/$1-run

	./debug/$1-run
fi
