#!/bin/bash

set -e

if [ ! -f train-labels-idx1-ubyte ]; then
	wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz

	gunzip train-labels-idx1-ubyte.gz
fi

if [ ! -f train-images-idx3-ubyte ]; then
	wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

	gunzip train-images-idx3-ubyte.gz
fi

if [ "$1" == "debug" ]; then
	g++-8 -I ../../engine main.cpp -pthread -g -o mnist
else
	g++-8 -I ../../engine main.cpp ../../bin/libzhp.a -pthread -O3 -o mnist
fi

mkdir -p bin

mv mnist bin/

if [ "$1" == "debug" ]; then
	valgrind --leak-check=full --track-origins=yes ./bin/mnist 2>vgrind.out
else
	./bin/mnist
fi
