#!/bin/bash

if [ ! -f train-labels-idx1-ubyte ]; then
	wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz

	gunzip train-labels-idx1-ubyte.gz
fi

if [ ! -f train-images-idx3-ubyte ]; then
	wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

	gunzip train-images-idx3-ubyte.gz
fi

cmake .

make

mkdir -p bin

mv mnist bin/

./bin/mnist
