#line 2 "function_lexer.h"

#line 4 "function_lexer.h"

#define  F_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define f_create_buffer f_create_buffer
#define f_delete_buffer f_delete_buffer
#define f_scan_buffer f_scan_buffer
#define f_scan_string f_scan_string
#define f_scan_bytes f_scan_bytes
#define f_init_buffer f_init_buffer
#define f_flush_buffer f_flush_buffer
#define f_load_buffer_state f_load_buffer_state
#define f_switch_to_buffer f_switch_to_buffer
#define fpush_buffer_state fpush_buffer_state
#define fpop_buffer_state fpop_buffer_state
#define fensure_buffer_stack fensure_buffer_stack
#define f_flex_debug f_flex_debug
#define fin fin
#define fleng fleng
#define flex flex
#define flineno flineno
#define fout fout
#define frestart frestart
#define ftext ftext
#define fwrap fwrap
#define falloc falloc
#define frealloc frealloc
#define ffree ffree

#define FLEX_SCANNER
#define F_FLEX_MAJOR_VERSION 2
#define F_FLEX_MINOR_VERSION 6
#define F_FLEX_SUBMINOR_VERSION 4
#if F_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef f_create_buffer
#define f_create_buffer_ALREADY_DEFINED
#else
#define f_create_buffer f_create_buffer
#endif

#ifdef f_delete_buffer
#define f_delete_buffer_ALREADY_DEFINED
#else
#define f_delete_buffer f_delete_buffer
#endif

#ifdef f_scan_buffer
#define f_scan_buffer_ALREADY_DEFINED
#else
#define f_scan_buffer f_scan_buffer
#endif

#ifdef f_scan_string
#define f_scan_string_ALREADY_DEFINED
#else
#define f_scan_string f_scan_string
#endif

#ifdef f_scan_bytes
#define f_scan_bytes_ALREADY_DEFINED
#else
#define f_scan_bytes f_scan_bytes
#endif

#ifdef f_init_buffer
#define f_init_buffer_ALREADY_DEFINED
#else
#define f_init_buffer f_init_buffer
#endif

#ifdef f_flush_buffer
#define f_flush_buffer_ALREADY_DEFINED
#else
#define f_flush_buffer f_flush_buffer
#endif

#ifdef f_load_buffer_state
#define f_load_buffer_state_ALREADY_DEFINED
#else
#define f_load_buffer_state f_load_buffer_state
#endif

#ifdef f_switch_to_buffer
#define f_switch_to_buffer_ALREADY_DEFINED
#else
#define f_switch_to_buffer f_switch_to_buffer
#endif

#ifdef fpush_buffer_state
#define fpush_buffer_state_ALREADY_DEFINED
#else
#define fpush_buffer_state fpush_buffer_state
#endif

#ifdef fpop_buffer_state
#define fpop_buffer_state_ALREADY_DEFINED
#else
#define fpop_buffer_state fpop_buffer_state
#endif

#ifdef fensure_buffer_stack
#define fensure_buffer_stack_ALREADY_DEFINED
#else
#define fensure_buffer_stack fensure_buffer_stack
#endif

#ifdef flex
#define flex_ALREADY_DEFINED
#else
#define flex flex
#endif

#ifdef frestart
#define frestart_ALREADY_DEFINED
#else
#define frestart frestart
#endif

#ifdef flex_init
#define flex_init_ALREADY_DEFINED
#else
#define flex_init flex_init
#endif

#ifdef flex_init_extra
#define flex_init_extra_ALREADY_DEFINED
#else
#define flex_init_extra flex_init_extra
#endif

#ifdef flex_destroy
#define flex_destroy_ALREADY_DEFINED
#else
#define flex_destroy flex_destroy
#endif

#ifdef fget_debug
#define fget_debug_ALREADY_DEFINED
#else
#define fget_debug fget_debug
#endif

#ifdef fset_debug
#define fset_debug_ALREADY_DEFINED
#else
#define fset_debug fset_debug
#endif

#ifdef fget_extra
#define fget_extra_ALREADY_DEFINED
#else
#define fget_extra fget_extra
#endif

#ifdef fset_extra
#define fset_extra_ALREADY_DEFINED
#else
#define fset_extra fset_extra
#endif

#ifdef fget_in
#define fget_in_ALREADY_DEFINED
#else
#define fget_in fget_in
#endif

#ifdef fset_in
#define fset_in_ALREADY_DEFINED
#else
#define fset_in fset_in
#endif

#ifdef fget_out
#define fget_out_ALREADY_DEFINED
#else
#define fget_out fget_out
#endif

#ifdef fset_out
#define fset_out_ALREADY_DEFINED
#else
#define fset_out fset_out
#endif

#ifdef fget_leng
#define fget_leng_ALREADY_DEFINED
#else
#define fget_leng fget_leng
#endif

#ifdef fget_text
#define fget_text_ALREADY_DEFINED
#else
#define fget_text fget_text
#endif

#ifdef fget_lineno
#define fget_lineno_ALREADY_DEFINED
#else
#define fget_lineno fget_lineno
#endif

#ifdef fset_lineno
#define fset_lineno_ALREADY_DEFINED
#else
#define fset_lineno fset_lineno
#endif

#ifdef fwrap
#define fwrap_ALREADY_DEFINED
#else
#define fwrap fwrap
#endif

#ifdef falloc
#define falloc_ALREADY_DEFINED
#else
#define falloc falloc
#endif

#ifdef frealloc
#define frealloc_ALREADY_DEFINED
#else
#define frealloc frealloc
#endif

#ifdef ffree
#define ffree_ALREADY_DEFINED
#else
#define ffree ffree
#endif

#ifdef ftext
#define ftext_ALREADY_DEFINED
#else
#define ftext ftext
#endif

#ifdef fleng
#define fleng_ALREADY_DEFINED
#else
#define fleng fleng
#endif

#ifdef fin
#define fin_ALREADY_DEFINED
#else
#define fin fin
#endif

#ifdef fout
#define fout_ALREADY_DEFINED
#else
#define fout fout
#endif

#ifdef f_flex_debug
#define f_flex_debug_ALREADY_DEFINED
#else
#define f_flex_debug f_flex_debug
#endif

#ifdef flineno
#define flineno_ALREADY_DEFINED
#else
#define flineno flineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define fconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define fnoreturn __attribute__((__noreturn__))
#else
#define fnoreturn
#endif

/* Returned upon end-of-file. */
#define F_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define F_SC_TO_UI(c) ((F_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (f_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The FSTATE alias is for lex
 * compatibility.
 */
#define F_START (((f_start) - 1) / 2)
#define FSTATE F_START
/* Action number for EOF rule of a given start state. */
#define F_STATE_EOF(state) (F_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define F_NEW_FILE frestart( fin  )
#define F_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef F_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, F_BUF_SIZE is 2*F_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define F_BUF_SIZE 32768
#else
#define F_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define F_STATE_BUF_SIZE   ((F_BUF_SIZE + 2) * sizeof(f_state_type))

#ifndef F_TYPEDEF_F_BUFFER_STATE
#define F_TYPEDEF_F_BUFFER_STATE
typedef struct f_buffer_state *F_BUFFER_STATE;
#endif

#ifndef F_TYPEDEF_F_SIZE_T
#define F_TYPEDEF_F_SIZE_T
typedef size_t f_size_t;
#endif

extern int fleng;

extern FILE *fin, *fout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define F_LESS_LINENO(n)
    #define F_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define fless(n) \
	do \
		{ \
		/* Undo effects of setting up ftext. */ \
        int fless_macro_arg = (n); \
        F_LESS_LINENO(fless_macro_arg);\
		*f_cp = (f_hold_char); \
		F_RESTORE_F_MORE_OFFSET \
		(f_c_buf_p) = f_cp = f_bp + fless_macro_arg - F_MORE_ADJ; \
		F_DO_BEFORE_ACTION; /* set up ftext again */ \
		} \
	while ( 0 )
#define unput(c) funput( c, (ftext_ptr)  )

#ifndef F_STRUCT_F_BUFFER_STATE
#define F_STRUCT_F_BUFFER_STATE
struct f_buffer_state
	{
	FILE *f_input_file;

	char *f_ch_buf;		/* input buffer */
	char *f_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int f_buf_size;

	/* Number of characters read into f_ch_buf, not including EOB
	 * characters.
	 */
	int f_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int f_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int f_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int f_at_bol;

    int f_bs_lineno; /**< The line count. */
    int f_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int f_fill_buffer;

	int f_buffer_status;

#define F_BUFFER_NEW 0
#define F_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as F_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via frestart()), so that the user can continue scanning by
	 * just pointing fin at a new input file.
	 */
#define F_BUFFER_EOF_PENDING 2

	};
#endif /* !F_STRUCT_F_BUFFER_STATE */

/* Stack of input buffers. */
static size_t f_buffer_stack_top = 0; /**< index of top of stack. */
static size_t f_buffer_stack_max = 0; /**< capacity of stack. */
static F_BUFFER_STATE * f_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define F_CURRENT_BUFFER ( (f_buffer_stack) \
                          ? (f_buffer_stack)[(f_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define F_CURRENT_BUFFER_LVALUE (f_buffer_stack)[(f_buffer_stack_top)]

/* f_hold_char holds the character lost when ftext is formed. */
static char f_hold_char;
static int f_n_chars;		/* number of characters read into f_ch_buf */
int fleng;

/* Points to current character in buffer. */
static char *f_c_buf_p = NULL;
static int f_init = 0;		/* whether we need to initialize */
static int f_start = 0;	/* start state number */

/* Flag which is used to allow fwrap()'s to do buffer switches
 * instead of setting up a fresh fin.  A bit of a hack ...
 */
static int f_did_buffer_switch_on_eof;

void frestart ( FILE *input_file  );
void f_switch_to_buffer ( F_BUFFER_STATE new_buffer  );
F_BUFFER_STATE f_create_buffer ( FILE *file, int size  );
void f_delete_buffer ( F_BUFFER_STATE b  );
void f_flush_buffer ( F_BUFFER_STATE b  );
void fpush_buffer_state ( F_BUFFER_STATE new_buffer  );
void fpop_buffer_state ( void );

static void fensure_buffer_stack ( void );
static void f_load_buffer_state ( void );
static void f_init_buffer ( F_BUFFER_STATE b, FILE *file  );
#define F_FLUSH_BUFFER f_flush_buffer( F_CURRENT_BUFFER )

F_BUFFER_STATE f_scan_buffer ( char *base, f_size_t size  );
F_BUFFER_STATE f_scan_string ( const char *f_str  );
F_BUFFER_STATE f_scan_bytes ( const char *bytes, int len  );

void *falloc ( f_size_t  );
void *frealloc ( void *, f_size_t  );
void ffree ( void *  );

#define f_new_buffer f_create_buffer
#define f_set_interactive(is_interactive) \
	{ \
	if ( ! F_CURRENT_BUFFER ){ \
        fensure_buffer_stack (); \
		F_CURRENT_BUFFER_LVALUE =    \
            f_create_buffer( fin, F_BUF_SIZE ); \
	} \
	F_CURRENT_BUFFER_LVALUE->f_is_interactive = is_interactive; \
	}
#define f_set_bol(at_bol) \
	{ \
	if ( ! F_CURRENT_BUFFER ){\
        fensure_buffer_stack (); \
		F_CURRENT_BUFFER_LVALUE =    \
            f_create_buffer( fin, F_BUF_SIZE ); \
	} \
	F_CURRENT_BUFFER_LVALUE->f_at_bol = at_bol; \
	}
#define F_AT_BOL() (F_CURRENT_BUFFER_LVALUE->f_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t F_CHAR;

FILE *fin = NULL, *fout = NULL;

typedef int f_state_type;

extern int flineno;
int flineno = 1;

extern char *ftext;
#ifdef ftext_ptr
#undef ftext_ptr
#endif
#define ftext_ptr ftext

static f_state_type f_get_previous_state ( void );
static f_state_type f_try_NUL_trans ( f_state_type current_state  );
static int f_get_next_buffer ( void );
static void fnoreturn f_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ftext.
 */
#define F_DO_BEFORE_ACTION \
	(ftext_ptr) = f_bp; \
	fleng = (int) (f_cp - f_bp); \
	(f_hold_char) = *f_cp; \
	*f_cp = '\0'; \
	(f_c_buf_p) = f_cp;
#define F_NUM_RULES 26
#define F_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct f_trans_info
	{
	flex_int32_t f_verify;
	flex_int32_t f_nxt;
	};
static const flex_int16_t f_accept[48] =
    {   0,
        0,    0,   27,   25,   24,   17,   18,   15,   14,   23,
       13,   25,   16,    1,   21,   22,   11,   12,   23,   23,
       23,   23,   19,   20,   23,    0,    1,    1,   23,   23,
        4,    3,   23,   23,   23,   23,    0,    6,   10,    8,
        2,    9,    5,    7,    0,    1,    0
    } ;

static const F_CHAR f_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    6,    7,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    7,   12,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       13,    1,   14,   15,   16,    1,   17,    7,   18,    7,

       19,    7,   20,    7,   21,    7,    7,   22,    7,   23,
       24,    7,    7,    7,   25,   26,    7,    7,    7,    7,
        7,    7,   27,    1,   28,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const F_CHAR f_meta[29] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1
    } ;

static const flex_int16_t f_base[49] =
    {   0,
        0,    0,   61,   62,   62,   62,   62,   62,   62,    0,
       20,   49,   62,   21,   62,   62,   62,   62,    9,   15,
       21,   42,   62,   62,    0,   47,   32,   25,   20,   39,
        0,    0,   36,   37,   31,   30,   41,    0,    0,    0,
        0,    0,    0,    0,   40,   39,   62,   46
    } ;

static const flex_int16_t f_def[49] =
    {   0,
       47,    1,   47,   47,   47,   47,   47,   47,   47,   48,
       47,   47,   47,   47,   47,   47,   47,   47,   48,   48,
       48,   48,   47,   47,   48,   47,   47,   47,   48,   48,
       48,   48,   48,   48,   48,   48,   47,   48,   48,   48,
       48,   48,   48,   48,   47,   47,    0,   47
    } ;

static const flex_int16_t f_nxt[91] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   10,   15,   16,   17,   18,   10,   19,   10,   10,
       10,   20,   10,   10,   21,   22,   23,   24,   26,   26,
       27,   27,   29,   30,   31,   28,   37,   32,   33,   34,
       26,   35,   27,   37,   38,   39,   45,   25,   45,   46,
       46,   46,   44,   43,   42,   41,   40,   28,   36,   28,
       47,    3,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47
    } ;

static const flex_int16_t f_chk[91] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   11,   14,
       11,   14,   19,   19,   20,   28,   28,   20,   20,   21,
       27,   21,   27,   28,   29,   29,   37,   48,   37,   46,
       45,   37,   36,   35,   34,   33,   30,   26,   22,   12,
        3,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47
    } ;

static f_state_type f_last_accepting_state;
static char *f_last_accepting_cpos;

extern int f_flex_debug;
int f_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define fmore() fmore_used_but_not_detected
#define F_MORE_ADJ 0
#define F_RESTORE_F_MORE_OFFSET
char *ftext;
#line 1 "function_lexer.l"
#line 2 "function_lexer.l"
	#include <iostream>
	#include <sstream>
	#include <string>

	using namespace std;
	
	extern "C" int flex();
#line 739 "function_lexer.h"
#line 740 "function_lexer.h"

#define INITIAL 0

#ifndef F_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef F_EXTRA_TYPE
#define F_EXTRA_TYPE void *
#endif

static int f_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int flex_destroy ( void );

int fget_debug ( void );

void fset_debug ( int debug_flag  );

F_EXTRA_TYPE fget_extra ( void );

void fset_extra ( F_EXTRA_TYPE user_defined  );

FILE *fget_in ( void );

void fset_in  ( FILE * _in_str  );

FILE *fget_out ( void );

void fset_out  ( FILE * _out_str  );

			int fget_leng ( void );

char *fget_text ( void );

int fget_lineno ( void );

void fset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef F_SKIP_FWRAP
#ifdef __cplusplus
extern "C" int fwrap ( void );
#else
extern int fwrap ( void );
#endif
#endif

#ifndef F_NO_UNPUT
    
    static void funput ( int c, char *buf_ptr  );
    
#endif

#ifndef ftext_ptr
static void f_flex_strncpy ( char *, const char *, int );
#endif

#ifdef F_NEED_STRLEN
static int f_flex_strlen ( const char * );
#endif

#ifndef F_NO_INPUT
#ifdef __cplusplus
static int finput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef F_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define F_READ_BUF_SIZE 16384
#else
#define F_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ftext, (size_t) fleng, 1, fout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or F_NULL,
 * is returned in "result".
 */
#ifndef F_INPUT
#define F_INPUT(buf,result,max_size) \
	if ( F_CURRENT_BUFFER_LVALUE->f_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( fin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( fin ) ) \
			F_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (f_size_t) max_size, fin)) == 0 && ferror(fin)) \
			{ \
			if( errno != EINTR) \
				{ \
				F_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(fin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "fterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef fterminate
#define fterminate() return F_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef F_START_STACK_INCR
#define F_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef F_FATAL_ERROR
#define F_FATAL_ERROR(msg) f_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef F_DECL
#define F_DECL_IS_OURS 1

extern int flex (void);

#define F_DECL int flex (void)
#endif /* !F_DECL */

/* Code executed at the beginning of each rule, after ftext and fleng
 * have been set up.
 */
#ifndef F_USER_ACTION
#define F_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef F_BREAK
#define F_BREAK /*LINTED*/break;
#endif

#define F_RULE_SETUP \
	F_USER_ACTION

/** The main scanner function which does all the work.
 */
F_DECL
{
	f_state_type f_current_state;
	char *f_cp, *f_bp;
	int f_act;
    
	if ( !(f_init) )
		{
		(f_init) = 1;

#ifdef F_USER_INIT
		F_USER_INIT;
#endif

		if ( ! (f_start) )
			(f_start) = 1;	/* first start state */

		if ( ! fin )
			fin = stdin;

		if ( ! fout )
			fout = stdout;

		if ( ! F_CURRENT_BUFFER ) {
			fensure_buffer_stack ();
			F_CURRENT_BUFFER_LVALUE =
				f_create_buffer( fin, F_BUF_SIZE );
		}

		f_load_buffer_state(  );
		}

	{
#line 13 "function_lexer.l"


#line 960 "function_lexer.h"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		f_cp = (f_c_buf_p);

		/* Support of ftext. */
		*f_cp = (f_hold_char);

		/* f_bp points to the position in f_ch_buf of the start of
		 * the current run.
		 */
		f_bp = f_cp;

		f_current_state = (f_start);
f_match:
		do
			{
			F_CHAR f_c = f_ec[F_SC_TO_UI(*f_cp)] ;
			if ( f_accept[f_current_state] )
				{
				(f_last_accepting_state) = f_current_state;
				(f_last_accepting_cpos) = f_cp;
				}
			while ( f_chk[f_base[f_current_state] + f_c] != f_current_state )
				{
				f_current_state = (int) f_def[f_current_state];
				if ( f_current_state >= 48 )
					f_c = f_meta[f_c];
				}
			f_current_state = f_nxt[f_base[f_current_state] + f_c];
			++f_cp;
			}
		while ( f_base[f_current_state] != 62 );

f_find_action:
		f_act = f_accept[f_current_state];
		if ( f_act == 0 )
			{ /* have to back up */
			f_cp = (f_last_accepting_cpos);
			f_current_state = (f_last_accepting_state);
			f_act = f_accept[f_current_state];
			}

		F_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( f_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of F_DO_BEFORE_ACTION */
			*f_cp = (f_hold_char);
			f_cp = (f_last_accepting_cpos);
			f_current_state = (f_last_accepting_state);
			goto f_find_action;

case 1:
F_RULE_SETUP
#line 15 "function_lexer.l"
{
		istringstream iss(ftext);
		iss >> flval.value;
		return F_NUMBER;
}
	F_BREAK
case 2:
F_RULE_SETUP
#line 21 "function_lexer.l"
{return F_LOG;}
	F_BREAK
case 3:
F_RULE_SETUP
#line 22 "function_lexer.l"
{return F_LN;}
	F_BREAK
case 4:
F_RULE_SETUP
#line 23 "function_lexer.l"
{return F_LG;}
	F_BREAK
case 5:
F_RULE_SETUP
#line 25 "function_lexer.l"
{return F_SIN;}
	F_BREAK
case 6:
F_RULE_SETUP
#line 26 "function_lexer.l"
{return F_COS;}
	F_BREAK
case 7:
F_RULE_SETUP
#line 27 "function_lexer.l"
{return F_TAN;}
	F_BREAK
case 8:
F_RULE_SETUP
#line 28 "function_lexer.l"
{return F_CSC;}
	F_BREAK
case 9:
F_RULE_SETUP
#line 29 "function_lexer.l"
{return F_SEC;}
	F_BREAK
case 10:
F_RULE_SETUP
#line 30 "function_lexer.l"
{return F_COT;}
	F_BREAK
case 11:
F_RULE_SETUP
#line 33 "function_lexer.l"
{return F_SUPERSCRIPT;}
	F_BREAK
case 12:
F_RULE_SETUP
#line 34 "function_lexer.l"
{return F_SUBSCRIPT;}
	F_BREAK
case 13:
F_RULE_SETUP
#line 36 "function_lexer.l"
{return F_MINUS;}
	F_BREAK
case 14:
F_RULE_SETUP
#line 37 "function_lexer.l"
{return F_PLUS;}
	F_BREAK
case 15:
F_RULE_SETUP
#line 38 "function_lexer.l"
{return F_MULT;}
	F_BREAK
case 16:
F_RULE_SETUP
#line 39 "function_lexer.l"
{return F_DIV;}
	F_BREAK
case 17:
F_RULE_SETUP
#line 41 "function_lexer.l"
{return F_LPAREN;}
	F_BREAK
case 18:
F_RULE_SETUP
#line 42 "function_lexer.l"
{return F_RPAREN;}
	F_BREAK
case 19:
F_RULE_SETUP
#line 44 "function_lexer.l"
{return F_LBRACE;}
	F_BREAK
case 20:
F_RULE_SETUP
#line 45 "function_lexer.l"
{return F_RBRACE;}
	F_BREAK
case 21:
F_RULE_SETUP
#line 47 "function_lexer.l"
{return F_LBRACKET;}
	F_BREAK
case 22:
F_RULE_SETUP
#line 48 "function_lexer.l"
{return F_RBRACKET;}
	F_BREAK
case 23:
F_RULE_SETUP
#line 50 "function_lexer.l"
{
		flval.ident = ftext;
		return F_IDENT;
}
	F_BREAK
case 24:
/* rule 24 can match eol */
F_RULE_SETUP
#line 55 "function_lexer.l"
{return F_END;}
	F_BREAK
case 25:
F_RULE_SETUP
#line 57 "function_lexer.l"
{}
	F_BREAK
case 26:
F_RULE_SETUP
#line 59 "function_lexer.l"
ECHO;
	F_BREAK
#line 1155 "function_lexer.h"
case F_STATE_EOF(INITIAL):
	fterminate();

	case F_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int f_amount_of_matched_text = (int) (f_cp - (ftext_ptr)) - 1;

		/* Undo the effects of F_DO_BEFORE_ACTION. */
		*f_cp = (f_hold_char);
		F_RESTORE_F_MORE_OFFSET

		if ( F_CURRENT_BUFFER_LVALUE->f_buffer_status == F_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed fin at a new source and called
			 * flex().  If so, then we have to assure
			 * consistency between F_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(f_n_chars) = F_CURRENT_BUFFER_LVALUE->f_n_chars;
			F_CURRENT_BUFFER_LVALUE->f_input_file = fin;
			F_CURRENT_BUFFER_LVALUE->f_buffer_status = F_BUFFER_NORMAL;
			}

		/* Note that here we test for f_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since f_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (f_c_buf_p) <= &F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars)] )
			{ /* This was really a NUL. */
			f_state_type f_next_state;

			(f_c_buf_p) = (ftext_ptr) + f_amount_of_matched_text;

			f_current_state = f_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * f_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			f_next_state = f_try_NUL_trans( f_current_state );

			f_bp = (ftext_ptr) + F_MORE_ADJ;

			if ( f_next_state )
				{
				/* Consume the NUL. */
				f_cp = ++(f_c_buf_p);
				f_current_state = f_next_state;
				goto f_match;
				}

			else
				{
				f_cp = (f_c_buf_p);
				goto f_find_action;
				}
			}

		else switch ( f_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(f_did_buffer_switch_on_eof) = 0;

				if ( fwrap(  ) )
					{
					/* Note: because we've taken care in
					 * f_get_next_buffer() to have set up
					 * ftext, we can now set up
					 * f_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * F_NULL, it'll still work - another
					 * F_NULL will get returned.
					 */
					(f_c_buf_p) = (ftext_ptr) + F_MORE_ADJ;

					f_act = F_STATE_EOF(F_START);
					goto do_action;
					}

				else
					{
					if ( ! (f_did_buffer_switch_on_eof) )
						F_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(f_c_buf_p) =
					(ftext_ptr) + f_amount_of_matched_text;

				f_current_state = f_get_previous_state(  );

				f_cp = (f_c_buf_p);
				f_bp = (ftext_ptr) + F_MORE_ADJ;
				goto f_match;

			case EOB_ACT_LAST_MATCH:
				(f_c_buf_p) =
				&F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars)];

				f_current_state = f_get_previous_state(  );

				f_cp = (f_c_buf_p);
				f_bp = (ftext_ptr) + F_MORE_ADJ;
				goto f_find_action;
			}
		break;
		}

	default:
		F_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of flex */

/* f_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int f_get_next_buffer (void)
{
    	char *dest = F_CURRENT_BUFFER_LVALUE->f_ch_buf;
	char *source = (ftext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (f_c_buf_p) > &F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars) + 1] )
		F_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( F_CURRENT_BUFFER_LVALUE->f_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (f_c_buf_p) - (ftext_ptr) - F_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((f_c_buf_p) - (ftext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( F_CURRENT_BUFFER_LVALUE->f_buffer_status == F_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		F_CURRENT_BUFFER_LVALUE->f_n_chars = (f_n_chars) = 0;

	else
		{
			int num_to_read =
			F_CURRENT_BUFFER_LVALUE->f_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			F_BUFFER_STATE b = F_CURRENT_BUFFER_LVALUE;

			int f_c_buf_p_offset =
				(int) ((f_c_buf_p) - b->f_ch_buf);

			if ( b->f_is_our_buffer )
				{
				int new_size = b->f_buf_size * 2;

				if ( new_size <= 0 )
					b->f_buf_size += b->f_buf_size / 8;
				else
					b->f_buf_size *= 2;

				b->f_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					frealloc( (void *) b->f_ch_buf,
							 (f_size_t) (b->f_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->f_ch_buf = NULL;

			if ( ! b->f_ch_buf )
				F_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(f_c_buf_p) = &b->f_ch_buf[f_c_buf_p_offset];

			num_to_read = F_CURRENT_BUFFER_LVALUE->f_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > F_READ_BUF_SIZE )
			num_to_read = F_READ_BUF_SIZE;

		/* Read in more data. */
		F_INPUT( (&F_CURRENT_BUFFER_LVALUE->f_ch_buf[number_to_move]),
			(f_n_chars), num_to_read );

		F_CURRENT_BUFFER_LVALUE->f_n_chars = (f_n_chars);
		}

	if ( (f_n_chars) == 0 )
		{
		if ( number_to_move == F_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			frestart( fin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			F_CURRENT_BUFFER_LVALUE->f_buffer_status =
				F_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((f_n_chars) + number_to_move) > F_CURRENT_BUFFER_LVALUE->f_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (f_n_chars) + number_to_move + ((f_n_chars) >> 1);
		F_CURRENT_BUFFER_LVALUE->f_ch_buf = (char *) frealloc(
			(void *) F_CURRENT_BUFFER_LVALUE->f_ch_buf, (f_size_t) new_size  );
		if ( ! F_CURRENT_BUFFER_LVALUE->f_ch_buf )
			F_FATAL_ERROR( "out of dynamic memory in f_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		F_CURRENT_BUFFER_LVALUE->f_buf_size = (int) (new_size - 2);
	}

	(f_n_chars) += number_to_move;
	F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars)] = F_END_OF_BUFFER_CHAR;
	F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars) + 1] = F_END_OF_BUFFER_CHAR;

	(ftext_ptr) = &F_CURRENT_BUFFER_LVALUE->f_ch_buf[0];

	return ret_val;
}

/* f_get_previous_state - get the state just before the EOB char was reached */

    static f_state_type f_get_previous_state (void)
{
	f_state_type f_current_state;
	char *f_cp;
    
	f_current_state = (f_start);

	for ( f_cp = (ftext_ptr) + F_MORE_ADJ; f_cp < (f_c_buf_p); ++f_cp )
		{
		F_CHAR f_c = (*f_cp ? f_ec[F_SC_TO_UI(*f_cp)] : 1);
		if ( f_accept[f_current_state] )
			{
			(f_last_accepting_state) = f_current_state;
			(f_last_accepting_cpos) = f_cp;
			}
		while ( f_chk[f_base[f_current_state] + f_c] != f_current_state )
			{
			f_current_state = (int) f_def[f_current_state];
			if ( f_current_state >= 48 )
				f_c = f_meta[f_c];
			}
		f_current_state = f_nxt[f_base[f_current_state] + f_c];
		}

	return f_current_state;
}

/* f_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = f_try_NUL_trans( current_state );
 */
    static f_state_type f_try_NUL_trans  (f_state_type f_current_state )
{
	int f_is_jam;
    	char *f_cp = (f_c_buf_p);

	F_CHAR f_c = 1;
	if ( f_accept[f_current_state] )
		{
		(f_last_accepting_state) = f_current_state;
		(f_last_accepting_cpos) = f_cp;
		}
	while ( f_chk[f_base[f_current_state] + f_c] != f_current_state )
		{
		f_current_state = (int) f_def[f_current_state];
		if ( f_current_state >= 48 )
			f_c = f_meta[f_c];
		}
	f_current_state = f_nxt[f_base[f_current_state] + f_c];
	f_is_jam = (f_current_state == 47);

		return f_is_jam ? 0 : f_current_state;
}

#ifndef F_NO_UNPUT

    static void funput (int c, char * f_bp )
{
	char *f_cp;
    
    f_cp = (f_c_buf_p);

	/* undo effects of setting up ftext */
	*f_cp = (f_hold_char);

	if ( f_cp < F_CURRENT_BUFFER_LVALUE->f_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (f_n_chars) + 2;
		char *dest = &F_CURRENT_BUFFER_LVALUE->f_ch_buf[
					F_CURRENT_BUFFER_LVALUE->f_buf_size + 2];
		char *source =
				&F_CURRENT_BUFFER_LVALUE->f_ch_buf[number_to_move];

		while ( source > F_CURRENT_BUFFER_LVALUE->f_ch_buf )
			*--dest = *--source;

		f_cp += (int) (dest - source);
		f_bp += (int) (dest - source);
		F_CURRENT_BUFFER_LVALUE->f_n_chars =
			(f_n_chars) = (int) F_CURRENT_BUFFER_LVALUE->f_buf_size;

		if ( f_cp < F_CURRENT_BUFFER_LVALUE->f_ch_buf + 2 )
			F_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--f_cp = (char) c;

	(ftext_ptr) = f_bp;
	(f_hold_char) = *f_cp;
	(f_c_buf_p) = f_cp;
}

#endif

#ifndef F_NO_INPUT
#ifdef __cplusplus
    static int finput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(f_c_buf_p) = (f_hold_char);

	if ( *(f_c_buf_p) == F_END_OF_BUFFER_CHAR )
		{
		/* f_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (f_c_buf_p) < &F_CURRENT_BUFFER_LVALUE->f_ch_buf[(f_n_chars)] )
			/* This was really a NUL. */
			*(f_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((f_c_buf_p) - (ftext_ptr));
			++(f_c_buf_p);

			switch ( f_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because f_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					frestart( fin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( fwrap(  ) )
						return 0;

					if ( ! (f_did_buffer_switch_on_eof) )
						F_NEW_FILE;
#ifdef __cplusplus
					return finput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(f_c_buf_p) = (ftext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (f_c_buf_p);	/* cast for 8-bit char's */
	*(f_c_buf_p) = '\0';	/* preserve ftext */
	(f_hold_char) = *++(f_c_buf_p);

	return c;
}
#endif	/* ifndef F_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void frestart  (FILE * input_file )
{
    
	if ( ! F_CURRENT_BUFFER ){
        fensure_buffer_stack ();
		F_CURRENT_BUFFER_LVALUE =
            f_create_buffer( fin, F_BUF_SIZE );
	}

	f_init_buffer( F_CURRENT_BUFFER, input_file );
	f_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void f_switch_to_buffer  (F_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		fpop_buffer_state();
	 *		fpush_buffer_state(new_buffer);
     */
	fensure_buffer_stack ();
	if ( F_CURRENT_BUFFER == new_buffer )
		return;

	if ( F_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(f_c_buf_p) = (f_hold_char);
		F_CURRENT_BUFFER_LVALUE->f_buf_pos = (f_c_buf_p);
		F_CURRENT_BUFFER_LVALUE->f_n_chars = (f_n_chars);
		}

	F_CURRENT_BUFFER_LVALUE = new_buffer;
	f_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (fwrap()) processing, but the only time this flag
	 * is looked at is after fwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(f_did_buffer_switch_on_eof) = 1;
}

static void f_load_buffer_state  (void)
{
    	(f_n_chars) = F_CURRENT_BUFFER_LVALUE->f_n_chars;
	(ftext_ptr) = (f_c_buf_p) = F_CURRENT_BUFFER_LVALUE->f_buf_pos;
	fin = F_CURRENT_BUFFER_LVALUE->f_input_file;
	(f_hold_char) = *(f_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c F_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    F_BUFFER_STATE f_create_buffer  (FILE * file, int  size )
{
	F_BUFFER_STATE b;
    
	b = (F_BUFFER_STATE) falloc( sizeof( struct f_buffer_state )  );
	if ( ! b )
		F_FATAL_ERROR( "out of dynamic memory in f_create_buffer()" );

	b->f_buf_size = size;

	/* f_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->f_ch_buf = (char *) falloc( (f_size_t) (b->f_buf_size + 2)  );
	if ( ! b->f_ch_buf )
		F_FATAL_ERROR( "out of dynamic memory in f_create_buffer()" );

	b->f_is_our_buffer = 1;

	f_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with f_create_buffer()
 * 
 */
    void f_delete_buffer (F_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == F_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		F_CURRENT_BUFFER_LVALUE = (F_BUFFER_STATE) 0;

	if ( b->f_is_our_buffer )
		ffree( (void *) b->f_ch_buf  );

	ffree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a frestart() or at EOF.
 */
    static void f_init_buffer  (F_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	f_flush_buffer( b );

	b->f_input_file = file;
	b->f_fill_buffer = 1;

    /* If b is the current buffer, then f_init_buffer was _probably_
     * called from frestart() or through f_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != F_CURRENT_BUFFER){
        b->f_bs_lineno = 1;
        b->f_bs_column = 0;
    }

        b->f_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, F_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c F_CURRENT_BUFFER.
 * 
 */
    void f_flush_buffer (F_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->f_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->f_ch_buf[0] = F_END_OF_BUFFER_CHAR;
	b->f_ch_buf[1] = F_END_OF_BUFFER_CHAR;

	b->f_buf_pos = &b->f_ch_buf[0];

	b->f_at_bol = 1;
	b->f_buffer_status = F_BUFFER_NEW;

	if ( b == F_CURRENT_BUFFER )
		f_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void fpush_buffer_state (F_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	fensure_buffer_stack();

	/* This block is copied from f_switch_to_buffer. */
	if ( F_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(f_c_buf_p) = (f_hold_char);
		F_CURRENT_BUFFER_LVALUE->f_buf_pos = (f_c_buf_p);
		F_CURRENT_BUFFER_LVALUE->f_n_chars = (f_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (F_CURRENT_BUFFER)
		(f_buffer_stack_top)++;
	F_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from f_switch_to_buffer. */
	f_load_buffer_state(  );
	(f_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void fpop_buffer_state (void)
{
    	if (!F_CURRENT_BUFFER)
		return;

	f_delete_buffer(F_CURRENT_BUFFER );
	F_CURRENT_BUFFER_LVALUE = NULL;
	if ((f_buffer_stack_top) > 0)
		--(f_buffer_stack_top);

	if (F_CURRENT_BUFFER) {
		f_load_buffer_state(  );
		(f_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void fensure_buffer_stack (void)
{
	f_size_t num_to_alloc;
    
	if (!(f_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(f_buffer_stack) = (struct f_buffer_state**)falloc
								(num_to_alloc * sizeof(struct f_buffer_state*)
								);
		if ( ! (f_buffer_stack) )
			F_FATAL_ERROR( "out of dynamic memory in fensure_buffer_stack()" );

		memset((f_buffer_stack), 0, num_to_alloc * sizeof(struct f_buffer_state*));

		(f_buffer_stack_max) = num_to_alloc;
		(f_buffer_stack_top) = 0;
		return;
	}

	if ((f_buffer_stack_top) >= ((f_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		f_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (f_buffer_stack_max) + grow_size;
		(f_buffer_stack) = (struct f_buffer_state**)frealloc
								((f_buffer_stack),
								num_to_alloc * sizeof(struct f_buffer_state*)
								);
		if ( ! (f_buffer_stack) )
			F_FATAL_ERROR( "out of dynamic memory in fensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((f_buffer_stack) + (f_buffer_stack_max), 0, grow_size * sizeof(struct f_buffer_state*));
		(f_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
F_BUFFER_STATE f_scan_buffer  (char * base, f_size_t  size )
{
	F_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != F_END_OF_BUFFER_CHAR ||
	     base[size-1] != F_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (F_BUFFER_STATE) falloc( sizeof( struct f_buffer_state )  );
	if ( ! b )
		F_FATAL_ERROR( "out of dynamic memory in f_scan_buffer()" );

	b->f_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->f_buf_pos = b->f_ch_buf = base;
	b->f_is_our_buffer = 0;
	b->f_input_file = NULL;
	b->f_n_chars = b->f_buf_size;
	b->f_is_interactive = 0;
	b->f_at_bol = 1;
	b->f_fill_buffer = 0;
	b->f_buffer_status = F_BUFFER_NEW;

	f_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to flex() will
 * scan from a @e copy of @a str.
 * @param fstr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       f_scan_bytes() instead.
 */
F_BUFFER_STATE f_scan_string (const char * fstr )
{
    
	return f_scan_bytes( fstr, (int) strlen(fstr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to flex() will
 * scan from a @e copy of @a bytes.
 * @param fbytes the byte buffer to scan
 * @param _fbytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
F_BUFFER_STATE f_scan_bytes  (const char * fbytes, int  _fbytes_len )
{
	F_BUFFER_STATE b;
	char *buf;
	f_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (f_size_t) (_fbytes_len + 2);
	buf = (char *) falloc( n  );
	if ( ! buf )
		F_FATAL_ERROR( "out of dynamic memory in f_scan_bytes()" );

	for ( i = 0; i < _fbytes_len; ++i )
		buf[i] = fbytes[i];

	buf[_fbytes_len] = buf[_fbytes_len+1] = F_END_OF_BUFFER_CHAR;

	b = f_scan_buffer( buf, n );
	if ( ! b )
		F_FATAL_ERROR( "bad buffer in f_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->f_is_our_buffer = 1;

	return b;
}

#ifndef F_EXIT_FAILURE
#define F_EXIT_FAILURE 2
#endif

static void fnoreturn f_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( F_EXIT_FAILURE );
}

/* Redefine fless() so it works in section 3 code. */

#undef fless
#define fless(n) \
	do \
		{ \
		/* Undo effects of setting up ftext. */ \
        int fless_macro_arg = (n); \
        F_LESS_LINENO(fless_macro_arg);\
		ftext[fleng] = (f_hold_char); \
		(f_c_buf_p) = ftext + fless_macro_arg; \
		(f_hold_char) = *(f_c_buf_p); \
		*(f_c_buf_p) = '\0'; \
		fleng = fless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int fget_lineno  (void)
{
    
    return flineno;
}

/** Get the input stream.
 * 
 */
FILE *fget_in  (void)
{
        return fin;
}

/** Get the output stream.
 * 
 */
FILE *fget_out  (void)
{
        return fout;
}

/** Get the length of the current token.
 * 
 */
int fget_leng  (void)
{
        return fleng;
}

/** Get the current token.
 * 
 */

char *fget_text  (void)
{
        return ftext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void fset_lineno (int  _line_number )
{
    
    flineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see f_switch_to_buffer
 */
void fset_in (FILE *  _in_str )
{
        fin = _in_str ;
}

void fset_out (FILE *  _out_str )
{
        fout = _out_str ;
}

int fget_debug  (void)
{
        return f_flex_debug;
}

void fset_debug (int  _bdebug )
{
        f_flex_debug = _bdebug ;
}

static int f_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from flex_destroy(), so don't allocate here.
     */

    (f_buffer_stack) = NULL;
    (f_buffer_stack_top) = 0;
    (f_buffer_stack_max) = 0;
    (f_c_buf_p) = NULL;
    (f_init) = 0;
    (f_start) = 0;

/* Defined in main.c */
#ifdef F_STDINIT
    fin = stdin;
    fout = stdout;
#else
    fin = NULL;
    fout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * flex_init()
     */
    return 0;
}

/* flex_destroy is for both reentrant and non-reentrant scanners. */
int flex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(F_CURRENT_BUFFER){
		f_delete_buffer( F_CURRENT_BUFFER  );
		F_CURRENT_BUFFER_LVALUE = NULL;
		fpop_buffer_state();
	}

	/* Destroy the stack itself. */
	ffree((f_buffer_stack) );
	(f_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * flex() is called, initialization will occur. */
    f_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef ftext_ptr
static void f_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef F_NEED_STRLEN
static int f_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *falloc (f_size_t  size )
{
			return malloc(size);
}

void *frealloc  (void * ptr, f_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void ffree (void * ptr )
{
			free( (char *) ptr );	/* see frealloc() for (char *) cast */
}

#define FTABLES_NAME "ftables"

#line 59 "function_lexer.l"


